version: "3"

services:
  incentives_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - backbone
    restart: unless-stopped

  mongodb:
    image: mongo:3.4
    ports: 
      - "27017:27017"
    networks:
      - backbone
    volumes:
      - ./mongodata:/data/db

networks:
  backbone:
    driver: bridge
