---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: incentives-api
  name: incentives-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: incentives-api
    spec:
      containers:
        - env:
            - name: MONGO_DB
              value: Ribbon-Incentives-API-DB
            - name: MONGO_HOSTNAME
              value: mongodb
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_PASSWORD
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_USERNAME
          image: registry.hub.docker.com/ribbonblockchain/incentives-alpha-api:latest
          name: incentives-api
          volumeMounts:
            - name: ca-pemstore
              mountPath: /home/API/config/cert.pem
              subPath: cert.pem
              readOnly: false
            - name: key-pemstore
              mountPath: /home/API/config/key.pem
              subPath: key.pem
              readOnly: false
          ports:
            - containerPort: 2053
          resources: {}
      restartPolicy: Always
      volumes:
        - name: ca-pemstore
          configMap:
            name: ca-pemstore
        - name: key-pemstore
          configMap:
            name: key-pemstore
status: {}
