version: 2.1
orbs:
  gcloud: circleci/gcp-cli@1.0.6
  gcp-gke: circleci/gcp-gke@0.2.0
  docker: circleci/docker@0.5.13
  k8s: circleci/kubernetes@0.1.0
jobs:  
  deploy-kubernetes:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      # Install `gcloud` and `kubectl` if not already installed.
      - gcp-gke/install
      # Initialize the `gcloud` CLI.
      - gcp-gke/init
      # Update a deployment Docker image.
      - gcp-gke/rollout-image:
          cluster: incentives-api-staging  
          deployment: incentives-api
          container: incentives-api
          image: registry.hub.docker.com/ribbonblockchain/incentives-alpha-api:latest
workflows:
  build_update_deploy:
    jobs:
      - docker/publish:
          image: ribbonblockchain/incentives-alpha-api
          tag: staging-$(echo $CIRCLE_SHA1 | cut -c -7)
          path: ./API
          deploy: true
      - deploy-kubernetes:
          requires:
            - docker/publish