db.activitylists.insertMany([{createdDate: new Date(),activityDescription:"", activityTitle:"Adherence scoring per milestone",activityReward:3},
{createdDate: new Date(),activityDescription:"", activityTitle:"Baby development full check",activityReward:2},
{createdDate: new Date(),activityDescription:"", activityTitle:"Blood donation",activityReward:5},
{createdDate: new Date(),activityDescription:"", activityTitle:"Blood draw test",activityReward:5},
{createdDate: new Date(),activityDescription:"", activityTitle:"Blood glucose check",activityReward:2},
{createdDate: new Date(),activityDescription:"", activityTitle:"Blood pressure check",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Body Mass Index (BMI) and waist",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Breast cancer lump physical check",activityReward:2},
{createdDate: new Date(),activityDescription:"", activityTitle:"Cancer check - non-intrusive",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Cancer test - intrusive",activityReward:5},
{createdDate: new Date(),activityDescription:"", activityTitle:"Child delivery",activityReward:5},
{createdDate: new Date(),activityDescription:"", activityTitle:"Cholesterol check",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Clinical Trial - intrusive",activityReward:5},
{createdDate: new Date(),activityDescription:"", activityTitle:"Clinical Trial - non-intrusive",activityReward:3},
{createdDate: new Date(),activityDescription:"", activityTitle:"Circumcision - Male",activityReward:5},
{createdDate: new Date(),activityDescription:"", activityTitle:"Colonoscopy check",activityReward:5},
{createdDate: new Date(),activityDescription:"", activityTitle:"Consultation ",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Counselling per visit",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Electrocardiogram (ECG)",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Excercise - Per week",activityReward:2},
{createdDate: new Date(),activityDescription:"", activityTitle:"Flu vaccination ",activityReward:3},
{createdDate: new Date(),activityDescription:"", activityTitle:"Glaucoma check",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Gynaecology check",activityReward:5},
{createdDate: new Date(),activityDescription:"", activityTitle:"Head size assessment check",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Height assessment check",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"HIV test - blood draw",activityReward:5},
{createdDate: new Date(),activityDescription:"", activityTitle:"HIV test - rapid prick test ",activityReward:2},
{createdDate: new Date(),activityDescription:"", activityTitle:"Immunization",activityReward:5},
{createdDate: new Date(),activityDescription:"", activityTitle:"Informed consent declaration",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Initiation of treatment",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Injection - in clinic per injection",activityReward:3},
{createdDate: new Date(),activityDescription:"", activityTitle:"Mammogram",activityReward:3},
{createdDate: new Date(),activityDescription:"", activityTitle:"Pap smear",activityReward:5},
{createdDate: new Date(),activityDescription:"", activityTitle:"Pharmacy drug collection",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Pre-natal class session",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Pregnancy Test",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Prevention - Other",activityReward:2},
{createdDate: new Date(),activityDescription:"", activityTitle:"Prevention - Pregnancy",activityReward:3},
{createdDate: new Date(),activityDescription:"", activityTitle:"Procedure - intrusive",activityReward:5},
{createdDate: new Date(),activityDescription:"", activityTitle:"Procedure - non-intrusive",activityReward:3},
{createdDate: new Date(),activityDescription:"", activityTitle:"Prostate inspection",activityReward:5},
{createdDate: new Date(),activityDescription:"", activityTitle:"Psychiatry therapy per visit",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Psychological therapy per visit",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Return checkup visit",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Return Visit",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Sign Non-smoker's declaration",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"STI Test",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Surgery",activityReward:5},
{createdDate: new Date(),activityDescription:"", activityTitle:"Survey",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"TB radiology test",activityReward:2},
{createdDate: new Date(),activityDescription:"", activityTitle:"TB test skin/sputum",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Testicular check",activityReward:3},
{createdDate: new Date(),activityDescription:"", activityTitle:"Ultrasound",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Urine Test",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Waist size assessment check",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Weight assessment check",activityReward:1},
{createdDate: new Date(),activityDescription:"", activityTitle:"Weight Management - per month", activityReward: 3}]);