db.prescriptionlists.insertMany([{dateCreated: new Date(), prescriptionDescription:"",prescriptionTitle:"Abacavir (ABC)"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"ACE-inhibitor"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Acetazolamide"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Acetic acid 2% in alcohol"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Aciclovir, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Activated charcoal"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Adrenaline (epinephrine), inhalation"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Adrenaline (epinephrine), parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Albendazole"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Allopurinol"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Amitriptyline"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Amlodipine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Amoxicillin"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Amoxicillin/clavulanic acid, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Amphotericin B"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Ampicillin"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Anticholinergic"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Anti-D immunoglobulin"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Antiviral (active against herpes zoster), oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Antiviral (active against varicella zoster), oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Aqueous Cream"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Artemether/lumefantrine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Artesunate"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Aspirin"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Atazanavir/ritonavir (ATV/r)"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Atenolol"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Atorvastatin"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Atropine, ophthalmic"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Atropine, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Azithromycin, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Bacillus camette-guerin (BCG), vaccine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Benzathine benzylpenicillin"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Benzodiazepine, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Benzodiazepine, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Benzoyl peroxide 5%, topical"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Benzyl benzoate"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Beta-blocker, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Betamethasone 0.1%, topical"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Betamethasone, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Biperiden, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Bismuth subgallate compound, topical"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Budesonide, inhaler"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Calamine lotion"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Calcium carbonate, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Calcium gluconate 10%, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Carbamazepine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Cardio-selective beta-blocker, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Carvedilol"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Ceftriaxone"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Cephalexin"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Cetirizine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Chloramphenicol 1%, ophthalmic"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Chlorhexidine 0.05% aqueous solution"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Chlorhexidine 0.2% mouthwash"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Chlorhexidine 0.5% in 70 % alcohol"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Chlorphenamine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Chlorpromazine, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Ciprofloxacin, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Citalopram"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Clotrimazole 1%, topical"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Clotrimazole vaginal cream"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Clotrimazole, vaginal pessary"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Coal tar (Liquor picis carbonis (LPC) BP"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Combined oral contraceptive"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Conjugated estrogens"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Corticosteroid potent, topical"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Corticosteroid potent, topical"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Corticosteroid, nasal solution"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Corticosteroid, inhaler"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Cotrimoxazole, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Cu T380A, IUCD"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Dextrose 5%"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Dextrose 10%"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Dextrose 50%"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Diazepam, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Diazepam, rectal"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Doxycycline"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Efavirenz (EFV)"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Emollient"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Emtricitabine (FTC)"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Emulsifying ointment"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Enalapril"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Ergometrine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Estradiol valerate"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Estradiol/norethisterone acetate"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Ethambutol"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Ethinylestradiol/levonorgestrel"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Etonogestrel subdermal implant"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Ferrous fumarate"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Ferrous gluconate"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Ferrous lactate"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Ferrous sulfate compound BPC"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Flucloxacillin"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Fluconazole, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Fluoxetine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Flupenthixol decanoate"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Fluphenazine decanoate"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Fluticasone, nasal solution"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Folic Acid"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Formoterol, inhaler"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Furosemide, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Furosemide, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Glibenclamide"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Glimepiride"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Glucose, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Haloperidol, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Haloperidol, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Hepatitis B (HepB) vaccine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Hepatitis B immunoglobulin (HBIG)"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Hexavalent - diptheria, tetanus, acellular pertussis, inactivated polio, hepatitis B, haemophilus influenza type b vaccine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"HMGCoA reductase Inhibitor"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Human papilloma virus vaccine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Hydrochlorothiazide"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Hydrocortisone"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Hydrocortisone 1%, topical"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Hyoscine butylbromide, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Hyoscine butylbromide, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Imidazole, topical"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Influenza vaccine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Insulin, biphasic"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Insulin, intermediate acting"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Insulin, short acting"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Ipratropium bromide, inhalant solution"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Ipratropium bromide, inhaler"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Iron, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Isoniazid"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Isosorbide dinitrate, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Isosorbide dinitrate, sublingual"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Isosorbide mononitrate, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"LABA/corticosteroid, inhaler"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Lactulose"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Lamivudine (3TC)"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Lamotrigine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Lansoprazole, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Levonorgestrel 1.5 mg, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Levothyroxine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Lidocaine 1% without adrenaline (epinephrine), parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Lidocaine 2%, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Lidocaine 2%, topical"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Lidocaine with adrenaline (epinephrine), parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Lidocaine, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Long-acting calcium channel blocker"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Loop diuretic, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Loperamide"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Lopinavir/ritonavir (LPV/r)"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Macrolide, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Magnesium sulfate, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Measles vaccine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Mebendazole"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Medroxyprogesterone acetate, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Medroxyprogesterone acetate, injectable"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Metformin"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Methyl salicylate ointment"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Methyldopa"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Metoclopramide, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Metoclopramide, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Metronidazole, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Midazolam, buccal"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Midazolam, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Mifepristone"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Misoprostol"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Monophasic: combined estrogen/progestin pill"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Monophasic: ethinyloestradiol/levonorgestrel, pill"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Monophasic: progestin only pill"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Monophasic: levonorgestrel, pill"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Morphine, long-acting, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Morphine, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Morphine, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Moxifloxacin, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Multivitamin"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Naloxone"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Nevirapine (NVP)"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Nicotinamide"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Nifedipine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Nifedipine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Nitrates short-acting"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Nitrofurantoin"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Nitrous oxide"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"NSAID, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Nystatin, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Oral polio vaccine (bOPV)"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Oral rehydrate solution (ORS)"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Orphenadrine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Oxygen"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Oxymetazoline 0.025%, nasal"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Oxymetazoline 0.025%, ophthalmic"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Oxymetazoline 0.05%, nasal"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Oxytocin"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Oxytocin/ergometrine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Paracetamol, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Permethrin"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Petroleum jelly"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Petroleum jelly, yellow"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Phenobarbital, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Phenoxymethylpenicillin"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Phenytoin, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Pneumococcal conjugated vaccine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Povidone-iodine, topical"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Prednisone, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Progestin-only, injectable "},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Progestin-only, subdermal implant "},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Promethazine, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Proton-pump inhibitor, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Pyrazinamide"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Pyridoxine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Quinine dihydrochloride, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Rabies immunoglobulin"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Rabies vaccine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Rifampicin"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Rifampicin/isoniazid "},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Rifampicin/isoniazid/pyrazinamide/ethambutol"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Risperidone, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Ritonavir"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Rotavirus vaccine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Salbutamol, inhalant solution"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Salbutamol, inhaler"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Salbutamol, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Salicylic acid 15-30%, topical"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Salicylic acid 2%, topical"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Salmeterol/fluticasone, inhaler"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Selenium sulphide 2.5%, topical"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Sennosides A and B"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Short-acting beta2 agonist, inhaler"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Simvastatin"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Soap substitute"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Sodium chloride 0.9%, nasal solution"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Sodium chloride 0.9%, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Sodium cromoglycate 2%, ophthalmic"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Spironolactone"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"SSRI"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Streptokinase"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Sulphonylurea"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Tenofovir (TDF)"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Tenofovir/emtriciabine/efavirenz (TDF+FTC+EFV)"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Tetanus and diptheria vaccine"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Tetanus toxoid"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Tetracaine 0.5%, topical"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Tetracaine 1%, ophthalmic"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Thiamine, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Thiamine, parenteral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Thrombolytic"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Tincture of Iodine BP"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Titanium dioxide (UV block)"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Tramadol, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Tretinoin, topical"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Tricyclic antidepressants"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Triphasic: combined estrogen/progestin pills"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Triphasic: ethinyloestradiol/levonorgestrel, pills"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Valproic acid, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Vitamin A"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Vitamin K"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Water for injection"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Zidovudine (AZT)"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Zinc, oral"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Zinc and castor oil, topical"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Zinc oxide, topical"},
{dateCreated: new Date(), prescriptionDescription:"", prescriptionTitle:"Zuclopenthixol decanoate"}]);