---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: incentives-api
  name: incentives-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: incentives-api
    spec:
      containers:
      - env:
        - name: MONGO_DB
        - name: MONGO_HOSTNAME
          value: mongodata
        - name: MONGO_PASSWORD
        - name: MONGO_PORT
        - name: MONGO_USERNAME
        image: ribbonblockchain/incentives-alpha-api:latest
        name: incentives-api
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
