apiVersion: v1
kind: Service
metadata:
  name: incentives-api
spec:
  type: LoadBalancer
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: incentives-api
status:
  loadBalancer: {}
